---
# install rsyslog
- name: RSysLog | Ensure software is installed using yum
  yum:
    name: rsyslog
    state: present
  when: ansible_os_family == 'RedHat'

- name: RSysLog | Ensure software is installed using apt
  apt:
    name: rsyslog
    state: present
  when: ansible_os_family == 'Debian'

# create configuration files
- name: RSysLog | Ensure configuration files exist for all service logs to be sent
  template:
    src: service.conf.j2
    dest: /etc/rsyslog.d/{{ item }}.conf
  with_items: rsyslog_sender_services.keys()
  notify:
    - restart rsyslog

- name: RSysLog | Ensure configuration files exist for logstash server
  template:
    src: logstash.conf.j2
    dest: /etc/rsyslog.d/logstash.conf
  when: rsyslog_sender_logstash_host is defined
  notify:
    - restart rsyslog
